### ISSUE TITLE
While scanning a multiline plain scalar, found invalid mapping

### ISSUE THREAD

**Issue by wroozle** [secure-cake/rapid-endpoint-investigations#1]
I tried to run the script and got the following error messages:

"While scanning a multiline plain scalar, found invalid mapping.
null

Verify all properties against example files or manual and try again

One or more targets or modules failed validation. Fix the issues and try again"

**Comment by secure-cake** [comment]
Howdy, wroozle! That sounds like a YAML file error. Can you confirm your KAPE install is complete/functional? If you can attach a screenshot of the script error, that might help too. Thank you!

**Comment by wroozle** [comment]
Sorry for the delayed response.  It was all me.
I downloaded html code instead of the actual file.  When I obtained the correct file, all was well.
Thank you for your prompt response.  Issue is RESOLVED!

**Comment by secure-cake** [comment]
No problem, wroozle! Glad you got it figured!
